<?php

namespace Test\Ease\FuelUX;

use Ease\FuelUX\Loader;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-06-20 at 13:42:07.
 */
class LoaderTest extends \Test\Ease\Html\DivTagTest
{
    /**
     * @var Loader
     */
    protected $object;
    public $rendered = '<div class="loader" data-initialize="loader" id="test"></div>';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        \Ease\Shared::webPage(new \Ease\TWB\WebPage());
        $this->object = new Loader('test');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Ease\FuelUX\Loader::finalize
     */
    public function testFinalize()
    {
        $this->object->finalize();
    }
}
